version: '3.7'
services:
  centos7:
    image: 'perfsonar/archive/qa:centos7'
    build:
      context: .
      dockerfile: docker/centos7/Dockerfile
    tmpfs: 
       - /run
       - /tmp:exec
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    working_dir: /app
    privileged: true
    ports:
        - "5601:5601"
        - "9200:9200"
        - "9300:9300"
